$paths = @(
"src/assets",
"src/components/ui/Button.jsx",
"src/components/ui/Input.jsx",
"src/components/ui/Select.jsx",
"src/components/ui/Checkbox.jsx",
"src/components/ui/Radio.jsx",
"src/components/ui/Textarea.jsx",
"src/components/ui/ToggleSwitch.jsx",
"src/components/ui/Loader.jsx",
"src/components/data/DataTable.jsx",
"src/components/data/Pagination.jsx",
"src/components/data/SearchBar.jsx",
"src/components/data/FilterPanel.jsx",
"src/components/forms/FormWrapper.jsx",
"src/components/forms/FormField.jsx",
"src/components/forms/FileUpload.jsx",
"src/components/forms/DatePicker.jsx",
"src/components/layout/Sidebar.jsx",
"src/components/layout/Navbar.jsx",
"src/components/layout/PageHeader.jsx",
"src/components/layout/Tabs.jsx",
"src/components/layout/Card.jsx",
"src/components/feedback/Toast.jsx",
"src/components/feedback/AlertBox.jsx",
"src/components/feedback/ConfirmDialog.jsx",
"src/components/feedback/EmptyState.jsx",
"src/components/charts/BarChart.jsx",
"src/components/charts/LineChart.jsx",
"src/components/charts/PieChart.jsx",
"src/components/advanced/BarcodeScanner.jsx",
"src/components/advanced/ChatWindow.jsx",
"src/components/advanced/NestingCanvas.jsx",
"src/components/advanced/StageTracker.jsx",
"src/modules/home/HomePage.jsx",
"src/modules/import/IPOImport.jsx",
"src/modules/import/BarcodeImport.jsx",
"src/modules/import/PnlImport.jsx",
"src/modules/plan/SortMaster.jsx",
"src/modules/plan/PnlPlanning.jsx",
"src/modules/plan/SecPlanning.jsx",
"src/modules/plan/SplPlanning.jsx",
"src/modules/material/RMCalculation.jsx",
"src/modules/material/ItemsModification.jsx",
"src/modules/reports/Production.jsx",
"src/modules/reports/MISReport.jsx",
"src/modules/reports/LotUnitReport.jsx",
"src/modules/reports/ProductionGraph.jsx",
"src/modules/ai/Chatbot.jsx",
"src/modules/scan/CheckItem.jsx",
"src/modules/rm/RMStock.jsx",
"src/modules/planSettings/ExclusionItems.jsx",
"src/modules/planSettings/SortMasterSettings.jsx",
"src/modules/planSettings/ChildParts.jsx",
"src/modules/settings/UserManagement.jsx",
"src/modules/settings/Appearance.jsx",
"src/modules/settings/Security.jsx",
"src/modules/settings/Company.jsx",
"src/modules/settings/Masters.jsx",
"src/modules/settings/Planning.jsx",
"src/modules/settings/Reports.jsx",
"src/modules/settings/AISettings.jsx",
"src/modules/settings/Notifications.jsx",
"src/modules/settings/Backup.jsx",
"src/modules/misc/Services.jsx",
"src/modules/misc/About.jsx",
"src/modules/misc/Contact.jsx",
"src/routes/AppRoutes.jsx",
"src/services/api.js",
"src/services/authService.js",
"src/services/settingsService.js",
"src/store/useAuthStore.js",
"src/store/useSettingsStore.js",
"src/hooks/useAuth.js",
"src/hooks/useSettings.js",
"src/utils/constants.js",
"src/utils/helpers.js",
"src/App.jsx",
"src/main.jsx"
)

foreach ($path in $paths) {
    if ($path.EndsWith("assets")) {
        New-Item -ItemType Directory -Force -Path $path | Out-Null
    } else {
        $dir = Split-Path $path -Parent
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Force -Path $dir | Out-Null
        }
        New-Item -ItemType File -Force -Path $path -Value "" | Out-Null
    }
}
